### ISSUE TITLE
delete-pr-image will fail miserably when `inputs.registry_token` is missing (esp in forks)

### ISSUE THREAD

**Issue by jsoref** [kpfleming/composite-actions#1]
This code will fail when `inputs.registry_token` is missing
https://github.com/kpfleming/composite-actions/blob/604952117beee85314427d06221a3ffa0b233ee4/delete-pr-image/action.yml#L17-L17

A normally configured repository would have this input, but when someone forks a repository that uses a workflow (that uses this action) and expects to have the secret, and then triggers the workflow, it'll fail miserably.

It's better to treat the lack of a secret as a success state and merely produce a step-summary with a note explaining that the input was missing (and if you want to check to see if you're in a fork and then suggest it's probably because of that, you could...).

**Comment by kpfleming** [comment]
The action has two existing 'features' which were an attempt to address this:

* The `registry_token` is marked as *required*, although I understand that Actions doesn't enforce that and will only issue a warning if it is not provided.

* The step which makes use of the `registry_token` is protected by `if: inputs.image_registry == 'quay.io'` so it will be skipped if that input does not match. I suspect it is unlikely that a fork will have `image_registry` configured but not have `registry_token` configured.

If these features are insufficient, I'm happy to consider additional protections.

**Comment by jsoref** [comment]
Yes, actions don't really use the required bit, and the things that do (visual studio code) generally don't have access to secrets and thus can't evaluate whether they're likely to work. 
I would personally use both fields in the `if`.
